server:
  port: 10001

spring:
  application:
    name: domain-user-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848

  datasource:
    # 拆分数据源到独立database instance或者schema
    username: root
    url: jdbc:mysql://127.0.0.1:3307/cloud-mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: 123456
#    url: ${mariadb.url}
#    password: ${mariadb.password}
    type: com.zaxxer.hikari.HikariDataSource
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true

# mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.hlkj.pojo

########################
###mybatis mapper配置
########################
#通用mapper配置
mapper:
  mappers: com.hlkj.common.mapper.MyMapper
  not-empty: false
  identity: MYSQL
#分页插件配置
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql


logging:
  level:
    com.hlkj.domain.item.mapper: debug

###########################
#####暴露actuator端点
#####hystrix监控使用
###########################
#配置中心github，无招胜有招（启动的时候从GitHub拉取这些属性，属性名称和GitHub配置一样，自动加载到项目中）
management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


seata:
  enabled: true
  service:
    vgroup-mapping:
      seata-product: default
    grouplist:
      default: 127.0.0.1:8091
    disable-global-transaction: false